name: project_1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  provider: ^6.1.2
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.20.2
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  path_provider: ^2.1.5
  device_info_plus: ^11.3.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/


